### ISSUE TITLE
修改源代码之后 使用psd2html xxx.png 引用的还是源代码  急求解决方案 谢谢

### ISSUE THREAD

**Issue by CharzleZhang** [purplebamboo/psd2html#2]
1.本地修改源代码 ruby psd2html.rb 想传递2个参数来测试demo 但是没有效果 
2.想修改ruby代码 实现功能如下
   2.1  在psd img-link| 之后可以添加链接 作为img-link的跳转地址 
   2.2  能够实现读取js文件  为页面中的元素动态绑定js代码
希望作者可以提供解决方案 多谢

**Comment by purplebamboo** [comment]
亲啊  这个项目已经不维护很久了呀。。。＝ ＝ 我都两年没碰ruby代码了。。

建议使用其他替代方案哈。

**Comment by purplebamboo** [comment]
试试这个哈 https://github.com/zswang/h5psd
